In [1]:
from __future__ import print_function
import torch

In [2]:
print(torch.__version__)

0.4.0


In [3]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [4]:
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [5]:
print(y.grad_fn)

In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [7]:
a = torch.randn(2,2)
print(a)

tensor([[ 0.8513,  1.3874],
        [ 0.0151,  0.9255]])


In [8]:
a = ((a * 3) / (a-1))
print(a)

tensor([[-17.1708,  10.7435],
        [ -0.0459, -37.2599]])


In [9]:
print(a.requires_grad)

False


In [10]:
a.requires_grad_(True)

tensor([[-17.1708,  10.7435],
        [ -0.0459, -37.2599]])

In [11]:
b = (a * a).sum()
print(b)

tensor(1798.5624)


In [12]:
print(b.grad_fn)

In [13]:
out.backward()

In [14]:
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [15]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 10:
    y = y * 2

print(y)

tensor([ 10.1973,  -4.0097,   0.8946])


In [16]:
z = x * 3
print(z)

tensor([ 7.6479, -3.0073,  0.6710])


In [18]:
z = z.sum()
z.backward()

In [21]:
print(x)
print(z)
print(x.grad)

tensor([ 2.5493, -1.0024,  0.2237])
tensor(5.3116)
tensor([ 3.,  3.,  3.])


In [22]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([ 3.4000,  7.0000,  3.0004])
